<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smb">

    <xacro:arg name="lidar" default="true"/>

    <xacro:include filename="$(find smb_description)/urdf/smb_utils.urdf.xacro" />
    <xacro:include filename="$(find smb_description)/urdf/sensor_plugins/smb_imu.gazebo.xacro"/>
    <xacro:include filename="$(find smb_description)/urdf/sensor_plugins/smb_gps.gazebo.xacro"/>
    <xacro:include filename="$(find smb_description)/urdf/sensor_plugins/camerazin.gazebo.xacro"/>
    <xacro:if value="$(arg lidar)">
        <xacro:include filename="$(find smb_description)/urdf/sensor_plugins/smb_velodyne.gazebo.xacro"/>
    </xacro:if>
    <xacro:include filename="$(find smb_description)/urdf/smb_lidar_mount.urdf.xacro"/>

    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- Model macros -->
    <xacro:macro name="wheel" params="prefix X Y wheel_joint_type friction_coeff:=0.2 transmission_reduction:=1" >
        <joint name="${prefix}_WHEEL_JOINT" type="${wheel_joint_type}">
            <parent link="${base_link_name}"/>
            <child link="${prefix}_WHEEL"/>
            <origin xyz="${X} ${Y} ${wheelHeight - chassisHeight/2.0}" rpy="-${0.5*PI} 0 0" />
            <axis xyz="0 0 1" rpy="0 0 0" />
            <dynamics damping="1.0" friction="0.0"/>
            <limit effort="1" velocity="1"/>
            <joint_properties damping="0.2" friction="0.2"/>
        </joint>

        <link name="${prefix}_WHEEL">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${wheelWidth/10}" radius="${wheelRadius}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="1.570796 0  0" />
                <geometry>
                    <mesh filename="package://smb_description/urdf/meshes/wheel.dae" />
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheelMass}"/>
                <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_WHEEL">
            <mu1 value="${friction_coeff}"/>
            <mu2 value="${friction_coeff}"/>
            <fdir1 value="1 0 0"/>
            <kp>10000000.0</kp>
            <kd>1.0</kd>
            <minDepth>0.005</minDepth>
            <maxVel>100.0</maxVel>
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <transmission name="${prefix}_WHEEL_TRANS" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_WHEEL_JOINT">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_ACTUATOR">
                <mechanicalReduction>${transmission_reduction}</mechanicalReduction>
            </actuator>
        </transmission>


    </xacro:macro>

























<!-- 
<xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>
<xacro:macro name="camera">
<link name="camera_smb">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link> 
</xacro:macro> -->




<!-- <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>
<link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link> -->



<!-- 


<link name='cam_link'>
  <pose frame=''>-0.118317 0.002195 0.004205 -0 -0 -3.12703</pose>
  <inertial>
    <mass>0.1</mass>
    <inertia>
      <ixx>1</ixx>
      <ixy>0</ixy>
      <ixz>0</ixz>
      <iyy>1</iyy>
      <iyz>0</iyz>
      <izz>1</izz>
    </inertia>
    <pose frame=''>0 0 0 0 -0 0</pose>
  </inertial>
  <self_collide>0</self_collide>
  <kinematic>0</kinematic>
  <sensor name='camera1' type='camera'>
    <camera name="head">
      <horizontal_fov>1.3962634</horizontal_fov>
      <image>
        <width>800</width>
        <height>800</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.02</near>
        <far>300</far>
      </clip>
    </camera>
    <always_on>1</always_on>
    <update_rate>30</update_rate>
    <visualize>1</visualize>
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>0.0</updateRate>
    <cameraName>smb/camera</cameraName>
    <imageTopicName>image_raw</imageTopicName>
    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
    <frameName>camera_link</frameName>
    <hackBaseline>0.07</hackBaseline>
    <distortionK1>0.0</distortionK1>
    <distortionK2>0.0</distortionK2>
    <distortionK3>0.0</distortionK3>
    <distortionT1>0.0</distortionT1>
    <distortionT2>0.0</distortionT2>
  </plugin>
  </sensor>
  </link> -->















    <xacro:macro name="chassis">

        <link name="${base_link_name}">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
                </geometry>
                <material name="base_material">
                    <color rgba="0.8 0.0 0.1 1.0"/>
                </material>
            </visual>
        </link>

        <link name="top">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${topLength} ${topWidth} ${topHeight}"/> 
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <!-- <box size="${topLength} ${topWidth} ${topHeight}"/> -->
                     <mesh filename="package://smb_description/urdf/new_payload/meshes/SMB_step.dae"/>
                </geometry>
            </visual>
        </link>

        <gazebo reference="top">
            <material>Gazebo/Grey</material>
        </gazebo>

        <gazebo reference="${base_link_name}">
            <material>Gazebo/Red</material>
        </gazebo>

    <joint name="top_to_base_link" type="fixed">
        <parent link="${base_link_name}"/>
        <child link="top"/>
        <!-- <origin xyz="${topXOffset/2.0} 0.0 ${chassisHeight/2.0 + topHeight/2.0}" rpy="0 0 0"/> -->
        <origin xyz="0.0 0.0 ${chassisHeight/2.0}" rpy="0 0 0"/>
    </joint>

    <!-- Fixed joint to add dummy inertia link -->
    <joint name="base_to_base_inertia" type="fixed">
      <parent link="${base_link_name}"/>
      <child link="base_inertia"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Dummy inertia link, because KDL cannot have inertia on the base link -->
    <link name="base_inertia">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${chassisMass}"/>
        <xacro:box_inertia m="${chassisMass}"
                     x="${chassisLength}"
                     y="${chassisWidth}"
                     z="${chassisHeight}"/>
      </inertial>
    </link>

    </xacro:macro>


    <xacro:macro name="smb" params="wheel_joint_type:=continuous lidar:=true simulation:=true">
        <xacro:chassis/>

        <xacro:wheel prefix="LF" X="${frontWheelX}"
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.5" />

        <xacro:wheel prefix="RF" X="${frontWheelX}"
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}"
            friction_coeff="0.5"/>

        <xacro:wheel prefix="LH" X="${backWheelX}"
            Y="${chassisWidth/2+wheelClearance+wheelWidth/2}"
	    wheel_joint_type="${wheel_joint_type}"
        friction_coeff="0.0" />

        <xacro:wheel prefix="RH" X="${backWheelX}"
            Y="${-chassisWidth/2-wheelClearance-wheelWidth/2}"
            wheel_joint_type="${wheel_joint_type}" />

        <xacro:IMU base_link="${base_link_name}" simulation="${simulation}"/>
        
        <xacro:CAM base_link="${base_link_name}" simulation="${simulation}"/>

        <!-- <xacro:GPS base_link="base" simulation="${simulation}"/> -->      

        <xacro:if value="${lidar}">
            <xacro:LIDAR base_link="${base_link_name}" simulation="${simulation}"/>
            <xacro:lidar_mount base_link="${base_link_name}"/>
        </xacro:if>

    </xacro:macro>
</robot>
